package upgrad;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class Driver {

    /**
     * Driver class main method
     *
     * @param args
     * @throws SQLException
     */
    public static void main(String[] args) throws SQLException {
        // MySql credentials
        String mySqlUrl = "jdbc:mysql://pgc-sd-bigdata.cyaielc9bmnf.us-east-1.rds.amazonaws.com:3306/pgcdata";
        String mySqlUser = "student";
        String mySqlPassword = "STUDENT123";

        // MongoDB Configurations
        String mongoUrl = "mongodb://ec2-3-239-94-172.compute-1.amazonaws.com";
        String mongoDatabase = "assignment";
        String mongoCollection = "products";

        // Connection Default Value Initialization
        Connection sqlConnection = null;
        MongoClient mongoClient = null;

        try {
            // Creating database connections
            sqlConnection = DriverManager.getConnection(mySqlUrl, mySqlUser, mySqlPassword);
            if (sqlConnection == null) {
                System.out.println("Could not establish MySql Connection");
                System.exit(0);
            }
            System.out.println("Successfully created MySql Connection");
            mongoClient = MongoClients.create(mongoUrl);
            MongoDatabase db = mongoClient.getDatabase(mongoDatabase);
            System.out.println("Successfully created MongoDb Connection\n");
            MongoCollection<Document> collection = db.getCollection(mongoCollection);

            // Import data into MongoDb
            extractAndMigrate(collection, sqlConnection, "cameras", "Cameras");
            extractAndMigrate(collection, sqlConnection, "mobiles", "Mobiles");
            extractAndMigrate(collection, sqlConnection, "headphones", "Headphones");


            // List all products in the inventory
            CRUDHelper.displayAllProducts(collection);

            // Display top 5 Mobiles
            CRUDHelper.displayTop5Mobiles(collection);

            // Display products ordered by their categories in Descending Order Without autogenerated Id
            CRUDHelper.displayCategoryOrderedProductsDescending(collection);

            // Display product count in each category
            CRUDHelper.displayProductCountByCategory(collection);

            // Display wired headphones
            CRUDHelper.displayWiredHeadphones(collection);
        } catch (Exception ex) {
            System.out.println("Got Exception.");
            ex.printStackTrace();
        } finally {
            // Close Connections
            if (sqlConnection != null) {
                System.out.println("Closing MySQL connection.");
                sqlConnection.close();
            }
            if (mongoClient != null) {
                System.out.println("Closing MongoDB connection.");
                mongoClient.close();
            }
        }
    }

    /**
     * Extract the data from MySql and load it in mongoDB
     *
     * @param collection - mongo collection where data is loaded
     * @param sqlConnection - connection object of MySql
     * @param tableName - MySQL table name
     * @param categoryName - Category name for each Document
     * @throws SQLException - exception from MySQL
     */
    private static void extractAndMigrate(MongoCollection<Document> collection, Connection sqlConnection, String tableName, String categoryName) throws SQLException {
        Statement cameraStatement = sqlConnection.createStatement();
        //Query for retrieval
        ResultSet resultSet = cameraStatement.executeQuery("select * from " + tableName);
        Document document;
        List<Document> documentList = new ArrayList<>();
        while (resultSet.next()) {
            document = new Document();
            // ResultSetMetaData to get column name and column count
            ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
            for (int i = 1; i <= resultSetMetaData.getColumnCount(); i++) {
                document.append(resultSetMetaData.getColumnName(i), resultSet.getString(resultSetMetaData.getColumnName(i)));
            }
            document.append("Category", categoryName);
            documentList.add(document);
        }
        System.out.println("total records read from MySQL table " + tableName + " : "+ documentList.size());
        System.out.println("Loading " + tableName + " into MongoDB products collection");
        //bulk insertion
        collection.insertMany(documentList);
        System.out.println("Migration Successful for " + tableName + " from MySql to MongoDB products collection\n");
    }
}